### ISSUE TITLE
better performance with file backed cache

### ISSUE THREAD

**Issue by blackmagic02881** [dask/s3fs#175]
current cache in s3fs is relatively limited. it constantly grows and shrinks to keep reasonable memory usage. unfortunately, it will have a huge read amplification ratio (with fill_cache = True) or poor performance with fill_cache = False for random workload. 
one way to solve this is to introduce an optional local file backed cache. for each s3 object  opened for read, a local tmp file with same size will be created and mmaped. a cache miss will fetch from s3 and copied into mmaped file. a mmaped file will provide much larger cache than current cache and much faster performance than S3. 

i can submit a PR if you have interest

**Comment by martindurant** [comment]
That is certainly an interesting idea! Would I be right in thinking that it only applies to posix systems?
Would you have any interest in generalising to any fetch-range file-like, as implemented in [fsspec](https://github.com/martindurant/filesystem_spec)'s `AbstractBufferedFile`? I suggest this, because the idea should be applicable to gcsfs, azure and other similar file-systems. (note #161 has preliminary support for s3fs-on-fsspec)

**Comment by martindurant** [comment]
Whichever you decide, this would be an optional, opt-in caching strategy, (`fill_cache='memmap'`), and should be careful to remove the file on close, and also to remove anything lingering at `__del__` or `atexit/weakref.finalize`.

**Comment by blackmagic02881** [comment]
in theory, it could apply to any slow storage that has a need for local cache. i will check fsspec and see whether it fits there. thanks for pointing out. 
also i use tempfile.TemporaryFile, which will be released as soon as file object get closed. the only concern is the disk space, if someone load a huge object and touch every part, it will take full space. that is why it is just optional.

**Comment by martindurant** [comment]
Implemented via fsspec
