### ISSUE TITLE
Glob returns no files if '?' before '*'

### ISSUE THREAD

**Issue by maciejb** [dask/s3fs#189]
Consider for example:
`fs.glob('mybucket/*/????/*.zip')`
returns
`['mybucket/folder/2018/file.zip', 'mybucket/folder/2019/file.zip']`
whereas
`fs.glob('mybucket/folder/????/*.zip')`
returns
`[]`

I believe this is due to the `star_pos = path.find('*')` part of the glob function. If the `*` is after the `?`, the `?` ends up in the path that gets walked, and so it doesn't find the path. 

I believe if you searched for `star_pos = min(path.find('*'), path.find('?'))` instead, that would take care of the problem?

**Comment by martindurant** [comment]
The place where this should be fixed is [here](https://github.com/intake/filesystem_spec/blob/master/fsspec/spec.py#L417), so that the same correct behaviour can be inherited by all file-systems - s3fs will soon depend on fsspec. Can you please raise an issue there? I will say, that globs are tricky to get right, given the `[` is also a character to look out for, but any of the three special characters could in theory be escaped. `*` is far less likely to feature as a legitimate part of a filename, though.

**Comment by maciejb** [comment]
Done. Thanks!
