### ISSUE TITLE
Pip install does not find matching distribution

### ISSUE THREAD

**Issue by baereilon** [dask/s3fs#212]
Tried to install the package, first through pipenv, then through pip, same error both times.
```
pip install s3f3
Collecting s3f3
  Could not find a version that satisfies the requirement s3f3 (from versions: )
No matching distribution found for s3f3
```
Tried specifying versions as well (0.3.1, 0.3.0, 0.2.2), same result.
Tried on different environments, local and in Docker container on EC2 instance.

pip version: 19.0.3
running on Mac OS Mojave 10.14.5

**Comment by martindurant** [comment]
Did you mean to install `s3fs` instead of `s3f3`?

(s3fs is a pure source distribution which certainly has installable versions even for py2 (although the most recent one is py>=3.5). I do not know what pip might be doing, but perhaps it has something to do with the many versions of boto, botocore and boto3 available. You might try pinning some of those in the install)

**Comment by baereilon** [comment]
You're absolutely right, thanks! And sorry for the inconvenience.
