### ISSUE TITLE
Syntax error in line 65 when importing

### ISSUE THREAD

**Issue by liber-dovat** [dask/s3fs#305]
https://github.com/dask/s3fs/blob/de3b1773a38011ea7c5b288513504e6a1310f961/s3fs/core.py#L65

When importing the module the system gives an SyntaxError exception:
```
    f"Cannot coalesce version_ids where more than one are defined, {version_ids}")
                                                                                ^
SyntaxError: invalid syntax

```

**Comment by TomAugspurger** [comment]
Same as https://github.com/dask/s3fs/issues/301

@martindurant it may be worth pulling 0.4.1 from PyPI, else users will continue to bump into this. I'm not sure what the downstream implications of this are though (for example, we wouldn't be able to rebuild a 0.4.1 conda package with a bumped build number, since the source is gone).
