### ISSUE TITLE
version 0.5.0 recursively copy remote folder fails

### ISSUE THREAD

**Issue by mgsnuno** [dask/s3fs#359]
**What happened**:
recursively copying a remote folder fails. it looks like async _get_file does handle directories paths properly.

new aio code (0.5.0):
```python
async def _get_file(self, rpath, lpath, version_id=None):
    bucket, key, vers = self.split_path(rpath)
    resp = await self._call_s3(
        self.s3.get_object, Bucket=bucket, Key=key,
        **version_id_kw(version_id or vers),
    )
    with open(lpath, "wb") as f0:
        body = resp['Body']
        while True:
            chunk = await body.read(2**16)
            if not chunk:
                break
            f0.write(chunk)
```

old code (0.4.2):
```python
def get_file(self, rpath, lpath, **kwargs):
    """Copy single remote file to local"""
    if self.isdir(rpath):
        os.makedirs(lpath, exist_ok=True)
    else:
        with self.open(rpath, "rb", **kwargs) as f1:
            with open(lpath, "wb") as f2:
                data = True
                while data:
                    data = f1.read(self.blocksize)
                    f2.write(data)
```

when copying recursively a remote folder with the latest aio code, rpath is not checked to be a directory and this causes `FileNotFoundError: The specified key does not exist.`

With version 0.4.2 this works fine.

Folder structure
```
folder
    subfolder
        file1
        ...
    subfolder1
        file1
        ...
    ...
```

**Environment**:
- Dask version: 2.25.0
- Python version: 3.8.5
- Operating System: manjaro
- Install method (conda, pip, source): conda

**Comment by martindurant** [comment]
It would be very helpful if you could set up your example as a test function, so that we can fix it and know that the fix works. Also, a traceback showing where the FielNotFound is coming from - is this on the local system, or is s3fs trying to download files that don't exist?
In making a fix, it must be remembered that: s3 does not have directories; and that it is possible to have a key with exactly the same name a "prefix".

Note that I intend to implement https://github.com/dask/gcsfs/pull/280 for s3fs, which should make this simpler.

**Comment by mgsnuno** [comment]
@martindurant issue still exists with s3fs 0.5.1 (which I assume has your changes to find).

The problem is like you mentioned 

>  s3fs trying to download files that don't exist?

Because _get_file is not checking if `rpath` is a directory or not (like previously), and `s3.get_object(.., key='path_directory')` will fail of course.

**Comment by martindurant** [comment]
I would suggest rather than checking each path to whether it is a key or not (which may be expensive - the best way to check is to try to download), we implement "ignoring" or exceptions in the bulk operations. For example, `rm` does not error if a key it tries to remove is already gone.

Alternatively, the keys to be got could be sorted such that folders always come last - if we already created a local folder, then we cannot overwrite it with the contents of a remote key with the same name, even if it exists.

What do you think?

**Comment by mgsnuno** [comment]
> we implement "ignoring" or exceptions in the bulk operations. For example, rm does not error if a key it tries to remove is already gone.

seems more robust, I'd go for that one, even though it might be slower. `try/except FileNotFoundError` blocks seems good.

It this an easy change on those functions I mentioned? any more pointers on what should be done? I can give it a try.

**Comment by martindurant** [comment]
https://github.com/intake/filesystem_spec/pull/409 does a similar thing for `cat`. There should be a reasonable way not to have to repeat the error-catching code for all batch functions.

**Comment by mgsnuno** [comment]
@martindurant is it possible to reopen this issue or a new one should be created? The issue is still not solved and I haven't implemented the suggested fix yet and it's better not to forget about this. Thanks

**Comment by martindurant** [comment]
Yes, it is the same; the directories should all be created up front, and then an attempt to download a key with the same name as a directory will be ignored. Since `isdir` is ambiguous on s3, this seems like the better approach.

> Do you still want to implement

Yes, this is reasonable. As I say, I would hope not to have to repeat the code, and this should be possible (although the default value might be "ignore" for rm and something else for the others).
