### ISSUE TITLE
hidden exception on `__del__`

### ISSUE THREAD

**Issue by martindurant** [dask/s3fs#4]
The following message sometimes displays, have not yet determined the conditions that cause it:
```
Exception ignored in: <bound method S3File.__del__ of <S3File test/temp>>
Traceback (most recent call last):
  File "/Users/mdurant/Downloads/s3fs/s3fs/core.py", line 580, in __del__
    self.close()
  File "/Users/mdurant/Downloads/s3fs/s3fs/core.py", line 574, in close
    UploadId=self.mpu['UploadId'], MultipartUpload=part_info)
  File "/Users/mdurant/Documents/anaconda/lib/python3.4/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/mdurant/Documents/anaconda/lib/python3.4/site-packages/botocore/client.py", line 407, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AllAccessDisabled) when calling the CompleteMultipartUpload operation: All access to this object has been disabled
```
This path only gets executed in write-mode.

**Comment by mrocklin** [comment]
We try to do a lot of non-trivial work in `__del__`, in particular flushing unwritten data.  This is dangerous because the s3 `Client` may have been cleaned up before this call.  Generally we shouldn't trust `__del__` too much with important code like this.  Probably the correct thing is to encourage users to use S3FileSystem as a context manager when writing.

**Comment by martindurant** [comment]
Files already work with `with`.
I think the reason was that `close()` was being called multiple times, and if already closed, should be a no-op. Fix coming when I get to it.
